name: Build cookbook PDF

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - 'assets'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  zip_and_upload_cls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Zip recipebook.cls
        run: |
          mkdir -p assets
          zip -j assets/cls.zip recipebook.cls

      - name: Upload cls.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: cls-zip
          path: assets/cls.zip

      - name: Ensure all images are JPG
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-tools
          mkdir -p ./images_converted
          for f in ./images/*; do
            if file -b "$f" | grep -q "JPEG image data"; then
              echo "$f is already a JPG, skipping."
              cp "$f" ./images_converted/
            else
              echo "Converting $f to JPG with max quality and stripping metadata..."
              filename=$(basename "$f")
              filename_no_ext="${filename%.*}"
              vips copy "$f" "./images_converted/${filename_no_ext}.jpg[Q=100,strip]"
            fi
          done
          rm -rf ./images
          mv ./images_converted ./images

      - name: Upload images artifact
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ./images

  build_latex:
    needs: zip_and_upload_cls
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download cls.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: cls-zip
          path: ./cls

      - name: Download images artifact
        uses: actions/download-artifact@v4
        with:
          name: images
          path: ./images

      - name: Unzip cls.zip
        run: unzip ./cls/cls.zip -d ./cls

      - name: Check paths
        run: |
          mkdir -p ./cls/images
          cp -r ./images/* ./cls/images/
          ls -latrhR ./cls

      - name: Compile LaTeX document with custom class
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./cls//:"

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: built-pdf
          path: main.pdf