name: Github Action for LaTeX

permissions:
  contents: write

on: [push]

jobs:
  zip_and_push_cls:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Zip recipebook.cls
        run: |
          mkdir -p assets
          zip -j assets/cls.zip recipebook.cls

      - name: Upload cls.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: cls-zip
          path: assets/cls.zip

  build_latex:
    runs-on: ubuntu-latest
    needs: zip_and_push_cls

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download cls.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: cls-zip
          path: ./cls

      - name: Unzip cls.zip
        run: unzip ./cls/cls.zip -d ./cls

      - name: Compile LaTeX document with custom class
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./cls//:"

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
